
import Head from 'next/head'
import React, { useEffect } from 'react'
import { getSession, useSession } from 'next-auth/react';
import AddForm from '../../components/AddForm'
import Headers from '../../components/Headers'
import { useRouter } from 'next/router'
const axios = require('axios');

function detailPage({data2}) {
  console.log(data2)

  const router = useRouter()
  const { authenticated,status, data: session } = useSession({
  required: true,})

  if (status=="loading" ) {
     return <div>...loading</div>}

  useEffect(() => {
    if (!session.user.admin) {
        router.push('/login');
      }
  }, []);

  if(session.user.admin){

    return (
    <div className="w-full relative bg-gray-50">
        <Head>
            <title>Admin</title>
            <meta name="description" content="Generated by create next app"/>
            <link rel="icon" href="/favicon.ico"/>
        </Head>
      <Headers />
        <div className='w-100 flex items-center justify-center mt-8'>
            <AddForm data2={data2}/>
        </div>
      </div>
      )} else{
        return (
          <div>...Page</div>
        )
      }
    }

export default detailPage

export async function getServerSideProps(context) {
const session = await getSession(context)
const {id} = context.params

const myId = id[0]
  const response = await axios.get(`${process.env.NEXTAUTH_URL}/api/customer3/${myId}`)
  const data2 = await response.data.respond1
  console.log(data2)
  // console.log("", response)
  // const data3 = JSON.stringify(data2)
  return {props:{session, data2}}
}