import { useSession } from 'next-auth/react'
import Head from 'next/head'
import { useRouter } from 'next/router'
import React, { useEffect } from 'react'
import FormAdd from '../components/FormAdd'
import Headers from '../components/Headers'



function addRm() {
  const {data: session, status} = useSession({ required: true })
  const router = useRouter()

  useEffect(()=>{
    if(!session){
        router.push("/login")
    }
},[])

  return (
    <div className="w-full relative bg-gray-50">
       <Head>
                    <title>ADD RM</title>
                    <meta name="description" content="Generated by create next app"/>
                    <link rel="icon" href="/favicon.ico"/>
          </Head>
      <Headers />
      <div className='w-100 flex items-center justify-center mt-8'>
        <FormAdd/>
      </div>
      <div className='flex flex-col items-center justify-center w-100'>
        {/* <TableNew/> */}
      
    </div> 
    </div>
    
  )
}

export default addRm