import Head from 'next/head'
import React, { useEffect } from 'react'
import { getSession, useSession } from 'next-auth/react';
import FormAdmin from '../components/FormAdmin'
import Headers from '../components/Headers'
import { useRouter } from 'next/router';

function admin() {
    const router = useRouter()
      const { authenticated,status, data: session } = useSession({
        required: true,
      })
  
      if (status=="loading" ) {
        return <div>...loading</div>;
      }
      useEffect(() => {
        if (!session.user.admin) {
            router.push('/login');
          }
      }, []);

      if(session.user.admin){
        return (
    <div className="w-full h-full relative bg-green-500">
        <Head>
            <title>Admin</title>
            <meta name="description" content="Generated by create next app"/>
            <link rel="icon" href="/favicon.ico"/>
        </Head>
      <Headers />
        <div className='w-100 flex items-center justify-center'>
            <FormAdmin/>
        </div>
     

    </div>
  )
}else{
  return <div>Login</div>
}
}

export default admin

export async function getServerSideProps(context) {
  const session = await getSession(context)
  if (!session) {
    return {
      redirect: {
        permanent: false,
        destination: "/login",
      },
    };
  }
  return {
      props:{session} // will be passed to the page component as props
    }
  }